project:
  type: website

website:
  description: "Bowen Ho's blog"
  site-url: https://bowen951209.github.io/bowen-blog/
  title: "Bowen Ho's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Bowen951209
format:
  html:
    theme:
      - cyborg
      - brand
    css: styles.css



